language: android
jdk: oraclejdk8
sudo: required

env:
  global:
    - "FTP_USER=root@filebooker.com"
    - "FTP_PASSWORD=9895204814"
    
notifications:
  email:
    - baneeishaque@gmail.com

android:
  components:
    - platform-tools
    - tools
    - build-tools-26.0.1
    - android-26
    - extra-android-m2repository

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:      #Cache all dirs under .gradle folder
    - $HOME/.gradle/daemon      #Cache daemon logs
    - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
    - $HOME/.gradle/wrapper     #Cache the gradle

before_install:
    #- mkdir "$ANDROID_HOME/licenses" || true
    #- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    #- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
    
    - mkdir -p ~/.gradle
    - echo "org.gradle.parallel=true" >> ~/.gradle/gradle.properties
    - echo "org.gradle.configureondemand=true" >> ~/.gradle/gradle.properties
    - cat ~/.gradle/gradle.properties
  
install:
    # Update sdk tools to latest version and install/update components
    #- echo yes | sdkmanager "tools"
    #- echo yes | sdkmanager "platforms;android-26" # Latest platform required by SDK tools
    #- echo yes | sdkmanager "build-tools;26.0.1"
    #- echo yes | sdkmanager "extras;android;m2repository"
    - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
    - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
    
    # Show version of Gradle
    - gradle --version
    
    # Show version and download Gradle Wrapper if it's not already cached
    - cd ${TRAVIS_BUILD_DIR}/${DIR} && ./gradlew --version
    
    # Clean project and download missing dependencies and components
    - cd ${TRAVIS_BUILD_DIR}/${DIR} && ./gradlew clean build
  
    # Check components status
    - sdkmanager --list || true
  
script: cd ${TRAVIS_BUILD_DIR}/${DIR} && ./gradlew build

after_success:
    - curl --ftp-create-dirs -T "{${TRAVIS_BUILD_DIR}/${DIR}/Admin/build/outputs/apk/Admin-debug.apk,${TRAVIS_BUILD_DIR}/${DIR}/User/build/outputs/apk/User-debug.apk}" -u $FTP_USER:$FTP_PASSWORD ftp://208.91.198.16/blood_bank/builds/travis/
